### ISSUE TITLE
Error when installing GX420t Zebra Printers

### ISSUE THREAD

**Issue by alanbradleyy** [futuretechlab/BravoPrinterEfficiencyTool#5]
The error occurs when attempting to install the Zebra GX420t Zebra Printers using the Printer Efficiency Tool version 1.2.2.0 on Windows 10.

![bravo pet tool error first run](https://user-images.githubusercontent.com/33699912/33996928-88c6027a-e097-11e7-9f15-12b6c5ddd92d.JPG)
![bravo pet tool error second run](https://user-images.githubusercontent.com/33699912/33996933-8bc2b522-e097-11e7-8c05-e628ad3602ea.JPG)

I've sent Stevo the videos containing the issue as they are too large for me to upload here on my own.

**Comment by futuretechlab** [comment]
This error has been corrected in the latest version 1.2.3
